"""empty message

Revision ID: 936fb10b9937
Revises: 
Create Date: 2026-03-23 15:26:59.063750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936fb10b9937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consejo_por_semana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('consejo', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tamanio_bebe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('fruta', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=20), nullable=True),
    sa.Column('tamano_cm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semana')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('embarazo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ultima_menstruacion', sa.Date(), nullable=False),
    sa.Column('fecha_parto_estimada', sa.Date(), nullable=True),
    sa.Column('peso_inicial', sa.Float(), nullable=False),
    sa.Column('longitud_ciclo', sa.Integer(), nullable=False),
    sa.Column('numero_bebes', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('tipo_informe', sa.String(length=50), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('url_pdf', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('estado_animo', sa.String(length=50), nullable=False),
    sa.Column('vasos_agua', sa.Integer(), nullable=False),
    sa.Column('patadas_bebe', sa.Integer(), nullable=False),
    sa.Column('horas_sueno', sa.Float(), nullable=False),
    sa.Column('ejercicio_minutos', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sintomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('nauseas', sa.Boolean(), nullable=False),
    sa.Column('fatiga', sa.Boolean(), nullable=False),
    sa.Column('dolor_espalda', sa.Boolean(), nullable=False),
    sa.Column('hinchazon', sa.Boolean(), nullable=False),
    sa.Column('acidez', sa.Boolean(), nullable=False),
    sa.Column('insomnio', sa.Boolean(), nullable=False),
    sa.Column('calambres', sa.Boolean(), nullable=False),
    sa.Column('antojos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['registro_diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sintomas')
    op.drop_table('registro_diario')
    op.drop_table('recordatorio')
    op.drop_table('informe')
    op.drop_table('embarazo')
    op.drop_table('user')
    op.drop_table('tamanio_bebe')
    op.drop_table('contact')
    op.drop_table('consejo_por_semana')
    # ### end Alembic commands ###
